name: Package - Test

on:
  push:
  #   paths:
  #     - "einvoice_lens/*.py"
  #     - "tests/**"
  #     - ".github/workflows/test.yml"
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python on version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.7.3,<0.9.0"
          enable-cache: true
          cache-dependency-glob: |
            requirements-dev.txt

      - name: Install dependencies
        run: |
          uv pip install --upgrade "pip>=25.1.1,<26.0.0";
          uv pip install "$(cat requirements-dev.txt | grep hatch)";

      - name: Test package
        run: |

          # Run
          hatch run test tests;
